import { PeptideProduct, FAQItem } from "./types";

export const PEPTIDES_DATA: PeptideProduct[] = [
  {
    "id": "bacteriostatic-water-10ml",
    "name": "10ml Bacteriostatic Mixing Water",
    "category": "Laboratory Supplies",
    "description": "Sterile, non-pyrogenic laboratory solution with 0.9% benzyl alcohol preservative for standard peptide reconstitution.",
    "longDescription": "Bacteriostatic Water is sterile, non-pyrogenic water containing 0.9% (9mg/mL) benzyl alcohol added as a bacteriostatic preservative. It is manufactured under strict laboratory standards specifically for reconstitution and stabilization of delicate lyophilized peptide compounds for in-vitro analytical research.",
    "purity": "99.9%",
    "formulation": "Sterile Reconstitution Liquid",
    "size": "10ml",
    "price": 5.95,
    "casNumber": "100-51-6 (Benzyl Alcohol)",
    "researchFocus": "Reconstitution and stabilization of analytical standards",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/bac%20water%2010ml-600x600.png"
  },
  {
    "id": "acetic-acid-10ml",
    "name": "10ml Acetic Acid 0.6%",
    "category": "Laboratory Supplies",
    "description": "Specialized hydrophilic reconstitution solution designed to improve the solubility of long-chain or hydrophobic peptides.",
    "longDescription": "Hydrophilic 0.6% Acetic Acid solution compiled to aid the solubility and reconstitution of highly hydrophobic or long-chain peptides that are prone to aggregation. Ensures clean, clear solution formation for accurate liquid chromatography and MS calibration.",
    "purity": "99.8%",
    "formulation": "Hydrophilic Reconstitution Liquid",
    "size": "10ml",
    "price": 6,
    "casNumber": "64-19-7",
    "researchFocus": "Hydrophobic peptide solubility optimization",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Acetic%20Acid-600x600.png"
  },
  {
    "id": "bpc-157-2mg",
    "name": "BPC-157 (Body Protection Compound) 2mg",
    "category": "Tissue Regeneration Pathways",
    "description": "A premium synthesised pentadecapeptide researched for tissue repair and gastrointestinal barrier integrity pathways.",
    "longDescription": "BPC-157 is a sequence of 15 amino acids derived from a protective protein discovered in human gastric juice. In laboratory in-vitro models, it has demonstrated significant signaling activity in blood vessel formation (angiogenesis) and cellular migration, making it a cornerstone for tissue healing and structural integration research.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 11.3,
    "casNumber": "137525-51-0",
    "researchFocus": "Tendon, ligament, and mucosal lining recovery pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/BPC-157-600x600.png"
  },
  {
    "id": "bpc-157-5mg",
    "name": "BPC-157 (Body Protection Compound) 5mg",
    "category": "Tissue Regeneration Pathways",
    "description": "A premium synthesised pentadecapeptide researched for tissue repair and gastrointestinal barrier integrity pathways.",
    "longDescription": "BPC-157 is a sequence of 15 amino acids derived from a protective protein discovered in human gastric juice. In laboratory in-vitro models, it has demonstrated significant signaling activity in blood vessel formation (angiogenesis) and cellular migration, making it a cornerstone for tissue healing and structural integration research.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 16.95,
    "casNumber": "137525-51-0",
    "researchFocus": "Tendon, ligament, and mucosal lining recovery pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/BPC-157-600x600.png"
  },
  {
    "id": "bpc-157-10mg",
    "name": "BPC-157 (Body Protection Compound) 10mg",
    "category": "Tissue Regeneration Pathways",
    "description": "A premium synthesised pentadecapeptide researched for tissue repair and gastrointestinal barrier integrity pathways.",
    "longDescription": "BPC-157 is a sequence of 15 amino acids derived from a protective protein discovered in human gastric juice. In laboratory in-vitro models, it has demonstrated significant signaling activity in blood vessel formation (angiogenesis) and cellular migration, making it a cornerstone for tissue healing and structural integration research.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 28.25,
    "casNumber": "137525-51-0",
    "researchFocus": "Tendon, ligament, and mucosal lining recovery pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/BPC-157-600x600.png"
  },
  {
    "id": "bpc-157-15mg",
    "name": "BPC-157 (Body Protection Compound) 15mg",
    "category": "Tissue Regeneration Pathways",
    "description": "A premium synthesised pentadecapeptide researched for tissue repair and gastrointestinal barrier integrity pathways.",
    "longDescription": "BPC-157 is a sequence of 15 amino acids derived from a protective protein discovered in human gastric juice. In laboratory in-vitro models, it has demonstrated significant signaling activity in blood vessel formation (angiogenesis) and cellular migration, making it a cornerstone for tissue healing and structural integration research.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 39.55,
    "casNumber": "137525-51-0",
    "researchFocus": "Tendon, ligament, and mucosal lining recovery pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/BPC-157-600x600.png"
  },
  {
    "id": "tb-500-2mg",
    "name": "Thymosin Beta 4 (TB-500) 2mg",
    "category": "Cellular Migration & Repair",
    "description": "A synthetic fragment of Thymosin Beta-4 studied for wound healing, cellular flexibility, and inflammatory signaling.",
    "longDescription": "TB-500 is a synthetic peptide containing the active sequence of Thymosin Beta-4, a naturally occurring protein present in almost all mammalian cells. It is researched extensively for its role in actin regulation, promoting endothelial cell differentiation, and supporting vascular development in targeted cellular models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 22,
    "casNumber": "77591-33-4",
    "researchFocus": "Angiogenesis, muscle fiber recovery, and cell motility",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/TB500-5mg-600x600.png"
  },
  {
    "id": "tb-500-5mg",
    "name": "Thymosin Beta 4 (TB-500) 5mg",
    "category": "Cellular Migration & Repair",
    "description": "A synthetic fragment of Thymosin Beta-4 studied for wound healing, cellular flexibility, and inflammatory signaling.",
    "longDescription": "TB-500 is a synthetic peptide containing the active sequence of Thymosin Beta-4, a naturally occurring protein present in almost all mammalian cells. It is researched extensively for its role in actin regulation, promoting endothelial cell differentiation, and supporting vascular development in targeted cellular models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 33,
    "casNumber": "77591-33-4",
    "researchFocus": "Angiogenesis, muscle fiber recovery, and cell motility",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/TB500-5mg-600x600.png"
  },
  {
    "id": "tb-500-10mg",
    "name": "Thymosin Beta 4 (TB-500) 10mg",
    "category": "Cellular Migration & Repair",
    "description": "A synthetic fragment of Thymosin Beta-4 studied for wound healing, cellular flexibility, and inflammatory signaling.",
    "longDescription": "TB-500 is a synthetic peptide containing the active sequence of Thymosin Beta-4, a naturally occurring protein present in almost all mammalian cells. It is researched extensively for its role in actin regulation, promoting endothelial cell differentiation, and supporting vascular development in targeted cellular models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 55,
    "casNumber": "77591-33-4",
    "researchFocus": "Angiogenesis, muscle fiber recovery, and cell motility",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/TB500-5mg-600x600.png"
  },
  {
    "id": "tb-500-15mg",
    "name": "Thymosin Beta 4 (TB-500) 15mg",
    "category": "Cellular Migration & Repair",
    "description": "A synthetic fragment of Thymosin Beta-4 studied for wound healing, cellular flexibility, and inflammatory signaling.",
    "longDescription": "TB-500 is a synthetic peptide containing the active sequence of Thymosin Beta-4, a naturally occurring protein present in almost all mammalian cells. It is researched extensively for its role in actin regulation, promoting endothelial cell differentiation, and supporting vascular development in targeted cellular models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 77,
    "casNumber": "77591-33-4",
    "researchFocus": "Angiogenesis, muscle fiber recovery, and cell motility",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/TB500-5mg-600x600.png"
  },
  {
    "id": "cjc-1295-2mg",
    "name": "CJC-1295 MOD GRF 1-29 / without DAC 2mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic tetrasubstituted peptide analogue of Growth Hormone Releasing Hormone (GHRH) studied for receptor affinity.",
    "longDescription": "CJC-1295 without DAC (also known as Modified GRF 1-29) is a synthetic analogue of growth hormone-releasing hormone (GHRH) with 29 amino acids. It stimulates growth hormone pathways with high selectivity, preserving pulsatile secretagogue profiles for clean biological affinity studies.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 12.95,
    "casNumber": "863288-34-0",
    "researchFocus": "Select GHRH receptor somatotropic signaling pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/CJC-MOD-GRF-600x600.png"
  },
  {
    "id": "cjc-1295-5mg",
    "name": "CJC-1295 MOD GRF 1-29 / without DAC 5mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic tetrasubstituted peptide analogue of Growth Hormone Releasing Hormone (GHRH) studied for receptor affinity.",
    "longDescription": "CJC-1295 without DAC (also known as Modified GRF 1-29) is a synthetic analogue of growth hormone-releasing hormone (GHRH) with 29 amino acids. It stimulates growth hormone pathways with high selectivity, preserving pulsatile secretagogue profiles for clean biological affinity studies.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 19.42,
    "casNumber": "863288-34-0",
    "researchFocus": "Select GHRH receptor somatotropic signaling pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/CJC-MOD-GRF-600x600.png"
  },
  {
    "id": "cjc-1295-10mg",
    "name": "CJC-1295 MOD GRF 1-29 / without DAC 10mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic tetrasubstituted peptide analogue of Growth Hormone Releasing Hormone (GHRH) studied for receptor affinity.",
    "longDescription": "CJC-1295 without DAC (also known as Modified GRF 1-29) is a synthetic analogue of growth hormone-releasing hormone (GHRH) with 29 amino acids. It stimulates growth hormone pathways with high selectivity, preserving pulsatile secretagogue profiles for clean biological affinity studies.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 32.38,
    "casNumber": "863288-34-0",
    "researchFocus": "Select GHRH receptor somatotropic signaling pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/CJC-MOD-GRF-600x600.png"
  },
  {
    "id": "cjc-1295-15mg",
    "name": "CJC-1295 MOD GRF 1-29 / without DAC 15mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic tetrasubstituted peptide analogue of Growth Hormone Releasing Hormone (GHRH) studied for receptor affinity.",
    "longDescription": "CJC-1295 without DAC (also known as Modified GRF 1-29) is a synthetic analogue of growth hormone-releasing hormone (GHRH) with 29 amino acids. It stimulates growth hormone pathways with high selectivity, preserving pulsatile secretagogue profiles for clean biological affinity studies.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 45.32,
    "casNumber": "863288-34-0",
    "researchFocus": "Select GHRH receptor somatotropic signaling pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/CJC-MOD-GRF-600x600.png"
  },
  {
    "id": "ipamorelin-2mg",
    "name": "Ipamorelin Acetate 2mg",
    "category": "Growth Hormone Signaling",
    "description": "A highly selective pentapeptide that acts as a ghrelin receptor agonist to stimulate growth hormone pathways.",
    "longDescription": "Ipamorelin is a synthetic peptide containing five amino acids. It is a selective growth hormone secretagogue that stimulates GH release in vitro with high specificity, avoiding the secondary stimulation of cortisol, ACTH, or prolactin, which makes it ideal for clean receptor affinity studies.",
    "purity": "99.5%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 9.95,
    "casNumber": "170851-70-4",
    "researchFocus": "Receptor-selective somatotropic signaling and bone density modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Ipamorelin-600x600.png"
  },
  {
    "id": "ipamorelin-5mg",
    "name": "Ipamorelin Acetate 5mg",
    "category": "Growth Hormone Signaling",
    "description": "A highly selective pentapeptide that acts as a ghrelin receptor agonist to stimulate growth hormone pathways.",
    "longDescription": "Ipamorelin is a synthetic peptide containing five amino acids. It is a selective growth hormone secretagogue that stimulates GH release in vitro with high specificity, avoiding the secondary stimulation of cortisol, ACTH, or prolactin, which makes it ideal for clean receptor affinity studies.",
    "purity": "99.5%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 14.92,
    "casNumber": "170851-70-4",
    "researchFocus": "Receptor-selective somatotropic signaling and bone density modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Ipamorelin-600x600.png"
  },
  {
    "id": "ipamorelin-10mg",
    "name": "Ipamorelin Acetate 10mg",
    "category": "Growth Hormone Signaling",
    "description": "A highly selective pentapeptide that acts as a ghrelin receptor agonist to stimulate growth hormone pathways.",
    "longDescription": "Ipamorelin is a synthetic peptide containing five amino acids. It is a selective growth hormone secretagogue that stimulates GH release in vitro with high specificity, avoiding the secondary stimulation of cortisol, ACTH, or prolactin, which makes it ideal for clean receptor affinity studies.",
    "purity": "99.5%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 24.88,
    "casNumber": "170851-70-4",
    "researchFocus": "Receptor-selective somatotropic signaling and bone density modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Ipamorelin-600x600.png"
  },
  {
    "id": "ipamorelin-15mg",
    "name": "Ipamorelin Acetate 15mg",
    "category": "Growth Hormone Signaling",
    "description": "A highly selective pentapeptide that acts as a ghrelin receptor agonist to stimulate growth hormone pathways.",
    "longDescription": "Ipamorelin is a synthetic peptide containing five amino acids. It is a selective growth hormone secretagogue that stimulates GH release in vitro with high specificity, avoiding the secondary stimulation of cortisol, ACTH, or prolactin, which makes it ideal for clean receptor affinity studies.",
    "purity": "99.5%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 34.82,
    "casNumber": "170851-70-4",
    "researchFocus": "Receptor-selective somatotropic signaling and bone density modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Ipamorelin-600x600.png"
  },
  {
    "id": "ghrp-6-2mg",
    "name": "GHRP-6 (Growth Hormone Releasing Peptide 6) 2mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic hexapeptide studied for ghrelin receptor affinity, cellular energy pathways, and growth hormone secretagogue dynamics.",
    "longDescription": "GHRP-6 is a synthetic met-enkephalin analogue containing six unnatural D-amino acids. It has been extensively studied in laboratory models for its binding affinity to the growth hormone secretagogue receptor (GHS-R), stimulating somatotropic pathways and cellular energy dynamics.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 6.63,
    "casNumber": "87616-84-0",
    "researchFocus": "GHS-R receptor binding and metabolic signaling cascades",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHRP6-600x600.png"
  },
  {
    "id": "ghrp-6-5mg",
    "name": "GHRP-6 (Growth Hormone Releasing Peptide 6) 5mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic hexapeptide studied for ghrelin receptor affinity, cellular energy pathways, and growth hormone secretagogue dynamics.",
    "longDescription": "GHRP-6 is a synthetic met-enkephalin analogue containing six unnatural D-amino acids. It has been extensively studied in laboratory models for its binding affinity to the growth hormone secretagogue receptor (GHS-R), stimulating somatotropic pathways and cellular energy dynamics.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 9.95,
    "casNumber": "87616-84-0",
    "researchFocus": "GHS-R receptor binding and metabolic signaling cascades",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHRP6-600x600.png"
  },
  {
    "id": "ghrp-6-10mg",
    "name": "GHRP-6 (Growth Hormone Releasing Peptide 6) 10mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic hexapeptide studied for ghrelin receptor affinity, cellular energy pathways, and growth hormone secretagogue dynamics.",
    "longDescription": "GHRP-6 is a synthetic met-enkephalin analogue containing six unnatural D-amino acids. It has been extensively studied in laboratory models for its binding affinity to the growth hormone secretagogue receptor (GHS-R), stimulating somatotropic pathways and cellular energy dynamics.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 16.58,
    "casNumber": "87616-84-0",
    "researchFocus": "GHS-R receptor binding and metabolic signaling cascades",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHRP6-600x600.png"
  },
  {
    "id": "ghrp-6-15mg",
    "name": "GHRP-6 (Growth Hormone Releasing Peptide 6) 15mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic hexapeptide studied for ghrelin receptor affinity, cellular energy pathways, and growth hormone secretagogue dynamics.",
    "longDescription": "GHRP-6 is a synthetic met-enkephalin analogue containing six unnatural D-amino acids. It has been extensively studied in laboratory models for its binding affinity to the growth hormone secretagogue receptor (GHS-R), stimulating somatotropic pathways and cellular energy dynamics.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 23.22,
    "casNumber": "87616-84-0",
    "researchFocus": "GHS-R receptor binding and metabolic signaling cascades",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHRP6-600x600.png"
  },
  {
    "id": "ghrp-2-2mg",
    "name": "GHRP-2 (Growth Hormone Releasing Peptide 2) 2mg",
    "category": "Growth Hormone Signaling",
    "description": "A highly researched synthetic secretagogue studied for growth hormone pathway activation and hypothalamic signaling.",
    "longDescription": "GHRP-2 (Pralmorelin) is a synthetic oligopeptide that binds to the growth hormone secretagogue receptor with extremely high potency. In in-vitro cell lines, it has been researched for its action on calcium ion flux, hypothalamic cell activation, and somatotropic release profiles.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 6.63,
    "casNumber": "158861-67-7",
    "researchFocus": "Hypothalamic receptor signaling and calcium channel influx",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHRP2-600x600.png"
  },
  {
    "id": "ghrp-2-5mg",
    "name": "GHRP-2 (Growth Hormone Releasing Peptide 2) 5mg",
    "category": "Growth Hormone Signaling",
    "description": "A highly researched synthetic secretagogue studied for growth hormone pathway activation and hypothalamic signaling.",
    "longDescription": "GHRP-2 (Pralmorelin) is a synthetic oligopeptide that binds to the growth hormone secretagogue receptor with extremely high potency. In in-vitro cell lines, it has been researched for its action on calcium ion flux, hypothalamic cell activation, and somatotropic release profiles.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 9.95,
    "casNumber": "158861-67-7",
    "researchFocus": "Hypothalamic receptor signaling and calcium channel influx",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHRP2-600x600.png"
  },
  {
    "id": "ghrp-2-10mg",
    "name": "GHRP-2 (Growth Hormone Releasing Peptide 2) 10mg",
    "category": "Growth Hormone Signaling",
    "description": "A highly researched synthetic secretagogue studied for growth hormone pathway activation and hypothalamic signaling.",
    "longDescription": "GHRP-2 (Pralmorelin) is a synthetic oligopeptide that binds to the growth hormone secretagogue receptor with extremely high potency. In in-vitro cell lines, it has been researched for its action on calcium ion flux, hypothalamic cell activation, and somatotropic release profiles.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 16.58,
    "casNumber": "158861-67-7",
    "researchFocus": "Hypothalamic receptor signaling and calcium channel influx",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHRP2-600x600.png"
  },
  {
    "id": "ghrp-2-15mg",
    "name": "GHRP-2 (Growth Hormone Releasing Peptide 2) 15mg",
    "category": "Growth Hormone Signaling",
    "description": "A highly researched synthetic secretagogue studied for growth hormone pathway activation and hypothalamic signaling.",
    "longDescription": "GHRP-2 (Pralmorelin) is a synthetic oligopeptide that binds to the growth hormone secretagogue receptor with extremely high potency. In in-vitro cell lines, it has been researched for its action on calcium ion flux, hypothalamic cell activation, and somatotropic release profiles.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 23.22,
    "casNumber": "158861-67-7",
    "researchFocus": "Hypothalamic receptor signaling and calcium channel influx",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHRP2-600x600.png"
  },
  {
    "id": "ace-031-2mg",
    "name": "ACE-031 (95% Untagged Premium) 2mg",
    "category": "Musculoskeletal Signaling Pathways",
    "description": "A soluble fusion protein researched for myostatin inhibition, skeletal muscle regulation, and growth pathways.",
    "longDescription": "ACE-031 is a recombinant fusion protein consisting of a portion of the human ActRIIB receptor attached to an antibody fragment. It is extensively researched in musculoskeletal biology for its ability to bind to myostatin (GDF-8) and other negative regulators of skeletal muscle mass, providing insights into myogenesis pathways.",
    "purity": "95.5%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 79,
    "casNumber": "1164565-17-2",
    "researchFocus": "Myostatin inhibition and skeletal cell differentiation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/ACE-031-600x600.png"
  },
  {
    "id": "ace-031-5mg",
    "name": "ACE-031 (95% Untagged Premium) 5mg",
    "category": "Musculoskeletal Signaling Pathways",
    "description": "A soluble fusion protein researched for myostatin inhibition, skeletal muscle regulation, and growth pathways.",
    "longDescription": "ACE-031 is a recombinant fusion protein consisting of a portion of the human ActRIIB receptor attached to an antibody fragment. It is extensively researched in musculoskeletal biology for its ability to bind to myostatin (GDF-8) and other negative regulators of skeletal muscle mass, providing insights into myogenesis pathways.",
    "purity": "95.5%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 118.5,
    "casNumber": "1164565-17-2",
    "researchFocus": "Myostatin inhibition and skeletal cell differentiation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/ACE-031-600x600.png"
  },
  {
    "id": "ace-031-10mg",
    "name": "ACE-031 (95% Untagged Premium) 10mg",
    "category": "Musculoskeletal Signaling Pathways",
    "description": "A soluble fusion protein researched for myostatin inhibition, skeletal muscle regulation, and growth pathways.",
    "longDescription": "ACE-031 is a recombinant fusion protein consisting of a portion of the human ActRIIB receptor attached to an antibody fragment. It is extensively researched in musculoskeletal biology for its ability to bind to myostatin (GDF-8) and other negative regulators of skeletal muscle mass, providing insights into myogenesis pathways.",
    "purity": "95.5%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 197.5,
    "casNumber": "1164565-17-2",
    "researchFocus": "Myostatin inhibition and skeletal cell differentiation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/ACE-031-600x600.png"
  },
  {
    "id": "ace-031-15mg",
    "name": "ACE-031 (95% Untagged Premium) 15mg",
    "category": "Musculoskeletal Signaling Pathways",
    "description": "A soluble fusion protein researched for myostatin inhibition, skeletal muscle regulation, and growth pathways.",
    "longDescription": "ACE-031 is a recombinant fusion protein consisting of a portion of the human ActRIIB receptor attached to an antibody fragment. It is extensively researched in musculoskeletal biology for its ability to bind to myostatin (GDF-8) and other negative regulators of skeletal muscle mass, providing insights into myogenesis pathways.",
    "purity": "95.5%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 276.5,
    "casNumber": "1164565-17-2",
    "researchFocus": "Myostatin inhibition and skeletal cell differentiation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/ACE-031-600x600.png"
  },
  {
    "id": "acth-1-2mg",
    "name": "ACTH (1-39) 2mg",
    "category": "Endocrine Signaling Pathways",
    "description": "A full-length adrenocorticotropic hormone peptide studied for adrenal cell signaling, steroidogenesis, and hypothalamic-pituitary pathways.",
    "longDescription": "Adrenocorticotropic Hormone (ACTH 1-39) is a 39-amino-acid peptide hormone synthesized in the pituitary gland. It is widely utilized in biological models to investigate adrenocortical cell response, steroidogenesis kinetics, and the complex feedback loops of the hypothalamic-pituitary-adrenal axis.",
    "purity": "98.9%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 56.67,
    "casNumber": "9002-60-2",
    "researchFocus": "Steroidogenesis pathways and neuroendocrine feedback systems",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/ATCH1-39-small-Recovered-600x600.png"
  },
  {
    "id": "acth-1-5mg",
    "name": "ACTH (1-39) 5mg",
    "category": "Endocrine Signaling Pathways",
    "description": "A full-length adrenocorticotropic hormone peptide studied for adrenal cell signaling, steroidogenesis, and hypothalamic-pituitary pathways.",
    "longDescription": "Adrenocorticotropic Hormone (ACTH 1-39) is a 39-amino-acid peptide hormone synthesized in the pituitary gland. It is widely utilized in biological models to investigate adrenocortical cell response, steroidogenesis kinetics, and the complex feedback loops of the hypothalamic-pituitary-adrenal axis.",
    "purity": "98.9%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 85,
    "casNumber": "9002-60-2",
    "researchFocus": "Steroidogenesis pathways and neuroendocrine feedback systems",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/ATCH1-39-small-Recovered-600x600.png"
  },
  {
    "id": "acth-1-10mg",
    "name": "ACTH (1-39) 10mg",
    "category": "Endocrine Signaling Pathways",
    "description": "A full-length adrenocorticotropic hormone peptide studied for adrenal cell signaling, steroidogenesis, and hypothalamic-pituitary pathways.",
    "longDescription": "Adrenocorticotropic Hormone (ACTH 1-39) is a 39-amino-acid peptide hormone synthesized in the pituitary gland. It is widely utilized in biological models to investigate adrenocortical cell response, steroidogenesis kinetics, and the complex feedback loops of the hypothalamic-pituitary-adrenal axis.",
    "purity": "98.9%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 141.67,
    "casNumber": "9002-60-2",
    "researchFocus": "Steroidogenesis pathways and neuroendocrine feedback systems",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/ATCH1-39-small-Recovered-600x600.png"
  },
  {
    "id": "acth-1-15mg",
    "name": "ACTH (1-39) 15mg",
    "category": "Endocrine Signaling Pathways",
    "description": "A full-length adrenocorticotropic hormone peptide studied for adrenal cell signaling, steroidogenesis, and hypothalamic-pituitary pathways.",
    "longDescription": "Adrenocorticotropic Hormone (ACTH 1-39) is a 39-amino-acid peptide hormone synthesized in the pituitary gland. It is widely utilized in biological models to investigate adrenocortical cell response, steroidogenesis kinetics, and the complex feedback loops of the hypothalamic-pituitary-adrenal axis.",
    "purity": "98.9%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 198.33,
    "casNumber": "9002-60-2",
    "researchFocus": "Steroidogenesis pathways and neuroendocrine feedback systems",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/ATCH1-39-small-Recovered-600x600.png"
  },
  {
    "id": "adamax-2mg",
    "name": "ADAMAX 2mg",
    "category": "Neurological & Cognitive Research",
    "description": "An advanced synthetic peptide derivative of Semax studied for neuroprotective, neurotrophic, and neuroplasticity modeling.",
    "longDescription": "Adamax is an upgraded synthetic analogue of Semax, modified with N-acetyl and C-terminal adamantane groups to enhance stability in laboratory assays. It is highly researched for its potential interaction with Brain-Derived Neurotrophic Factor (BDNF) expression and dopamine receptor pathways.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 32.67,
    "casNumber": "115102-14-2 (Adamantane base)",
    "researchFocus": "Neurotrophic factor BDNF expression and cerebral cell resilience",
    "image": "https://www.uk-peptides.com/image/cache/catalog/adamx-new-600x600.jpg"
  },
  {
    "id": "adamax-5mg",
    "name": "ADAMAX 5mg",
    "category": "Neurological & Cognitive Research",
    "description": "An advanced synthetic peptide derivative of Semax studied for neuroprotective, neurotrophic, and neuroplasticity modeling.",
    "longDescription": "Adamax is an upgraded synthetic analogue of Semax, modified with N-acetyl and C-terminal adamantane groups to enhance stability in laboratory assays. It is highly researched for its potential interaction with Brain-Derived Neurotrophic Factor (BDNF) expression and dopamine receptor pathways.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 49,
    "casNumber": "115102-14-2 (Adamantane base)",
    "researchFocus": "Neurotrophic factor BDNF expression and cerebral cell resilience",
    "image": "https://www.uk-peptides.com/image/cache/catalog/adamx-new-600x600.jpg"
  },
  {
    "id": "adamax-10mg",
    "name": "ADAMAX 10mg",
    "category": "Neurological & Cognitive Research",
    "description": "An advanced synthetic peptide derivative of Semax studied for neuroprotective, neurotrophic, and neuroplasticity modeling.",
    "longDescription": "Adamax is an upgraded synthetic analogue of Semax, modified with N-acetyl and C-terminal adamantane groups to enhance stability in laboratory assays. It is highly researched for its potential interaction with Brain-Derived Neurotrophic Factor (BDNF) expression and dopamine receptor pathways.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 81.67,
    "casNumber": "115102-14-2 (Adamantane base)",
    "researchFocus": "Neurotrophic factor BDNF expression and cerebral cell resilience",
    "image": "https://www.uk-peptides.com/image/cache/catalog/adamx-new-600x600.jpg"
  },
  {
    "id": "adamax-15mg",
    "name": "ADAMAX 15mg",
    "category": "Neurological & Cognitive Research",
    "description": "An advanced synthetic peptide derivative of Semax studied for neuroprotective, neurotrophic, and neuroplasticity modeling.",
    "longDescription": "Adamax is an upgraded synthetic analogue of Semax, modified with N-acetyl and C-terminal adamantane groups to enhance stability in laboratory assays. It is highly researched for its potential interaction with Brain-Derived Neurotrophic Factor (BDNF) expression and dopamine receptor pathways.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 114.33,
    "casNumber": "115102-14-2 (Adamantane base)",
    "researchFocus": "Neurotrophic factor BDNF expression and cerebral cell resilience",
    "image": "https://www.uk-peptides.com/image/cache/catalog/adamx-new-600x600.jpg"
  },
  {
    "id": "aod-9604-2mg",
    "name": "AOD-9604 2mg",
    "category": "Metabolic & Lipolytic Pathways",
    "description": "A synthetic peptide fragment derived from the C-terminus of Growth Hormone researched for lipolysis signaling.",
    "longDescription": "AOD-9604 is a synthetic analog of the lipolytic fragment of growth hormone (Tyr-hGH177-191). It is highly studied in cellular metabolic models for its ability to trigger lipolysis and inhibit lipogenesis in isolated fat cells without activating IGF-1 or somatotropic growth pathways.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 27.95,
    "casNumber": "221231-10-3",
    "researchFocus": "Lipolytic pathway signaling and metabolic rate regulation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/AOD-small-600x600.png"
  },
  {
    "id": "aod-9604-5mg",
    "name": "AOD-9604 5mg",
    "category": "Metabolic & Lipolytic Pathways",
    "description": "A synthetic peptide fragment derived from the C-terminus of Growth Hormone researched for lipolysis signaling.",
    "longDescription": "AOD-9604 is a synthetic analog of the lipolytic fragment of growth hormone (Tyr-hGH177-191). It is highly studied in cellular metabolic models for its ability to trigger lipolysis and inhibit lipogenesis in isolated fat cells without activating IGF-1 or somatotropic growth pathways.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 41.92,
    "casNumber": "221231-10-3",
    "researchFocus": "Lipolytic pathway signaling and metabolic rate regulation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/AOD-small-600x600.png"
  },
  {
    "id": "aod-9604-10mg",
    "name": "AOD-9604 10mg",
    "category": "Metabolic & Lipolytic Pathways",
    "description": "A synthetic peptide fragment derived from the C-terminus of Growth Hormone researched for lipolysis signaling.",
    "longDescription": "AOD-9604 is a synthetic analog of the lipolytic fragment of growth hormone (Tyr-hGH177-191). It is highly studied in cellular metabolic models for its ability to trigger lipolysis and inhibit lipogenesis in isolated fat cells without activating IGF-1 or somatotropic growth pathways.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 69.88,
    "casNumber": "221231-10-3",
    "researchFocus": "Lipolytic pathway signaling and metabolic rate regulation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/AOD-small-600x600.png"
  },
  {
    "id": "aod-9604-15mg",
    "name": "AOD-9604 15mg",
    "category": "Metabolic & Lipolytic Pathways",
    "description": "A synthetic peptide fragment derived from the C-terminus of Growth Hormone researched for lipolysis signaling.",
    "longDescription": "AOD-9604 is a synthetic analog of the lipolytic fragment of growth hormone (Tyr-hGH177-191). It is highly studied in cellular metabolic models for its ability to trigger lipolysis and inhibit lipogenesis in isolated fat cells without activating IGF-1 or somatotropic growth pathways.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 97.83,
    "casNumber": "221231-10-3",
    "researchFocus": "Lipolytic pathway signaling and metabolic rate regulation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/AOD-small-600x600.png"
  },
  {
    "id": "ara-290-2mg",
    "name": "ARA-290 (Cibinetide) 2mg",
    "category": "Neurological & Cognitive Research",
    "description": "A synthetic peptide modeled after erythropoietin researched for tissue protection, nerve regeneration, and inflammatory pathways.",
    "longDescription": "ARA-290 is an 11-amino-acid peptide designed from the tertiary structure of erythropoietin (EPO). It specifically activates the innate repair receptor (IRR) without stimulating erythropoiesis, making it a critical tool for investigating neurological repair and inflammatory signal suppression.",
    "purity": "99.0%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 75,
    "casNumber": "1208243-50-8",
    "researchFocus": "Innate repair receptor activation and peripheral neuropathy pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/ara29-600x600.jpg"
  },
  {
    "id": "ara-290-5mg",
    "name": "ARA-290 (Cibinetide) 5mg",
    "category": "Neurological & Cognitive Research",
    "description": "A synthetic peptide modeled after erythropoietin researched for tissue protection, nerve regeneration, and inflammatory pathways.",
    "longDescription": "ARA-290 is an 11-amino-acid peptide designed from the tertiary structure of erythropoietin (EPO). It specifically activates the innate repair receptor (IRR) without stimulating erythropoiesis, making it a critical tool for investigating neurological repair and inflammatory signal suppression.",
    "purity": "99.0%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 112.5,
    "casNumber": "1208243-50-8",
    "researchFocus": "Innate repair receptor activation and peripheral neuropathy pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/ara29-600x600.jpg"
  },
  {
    "id": "ara-290-10mg",
    "name": "ARA-290 (Cibinetide) 10mg",
    "category": "Neurological & Cognitive Research",
    "description": "A synthetic peptide modeled after erythropoietin researched for tissue protection, nerve regeneration, and inflammatory pathways.",
    "longDescription": "ARA-290 is an 11-amino-acid peptide designed from the tertiary structure of erythropoietin (EPO). It specifically activates the innate repair receptor (IRR) without stimulating erythropoiesis, making it a critical tool for investigating neurological repair and inflammatory signal suppression.",
    "purity": "99.0%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 187.5,
    "casNumber": "1208243-50-8",
    "researchFocus": "Innate repair receptor activation and peripheral neuropathy pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/ara29-600x600.jpg"
  },
  {
    "id": "ara-290-15mg",
    "name": "ARA-290 (Cibinetide) 15mg",
    "category": "Neurological & Cognitive Research",
    "description": "A synthetic peptide modeled after erythropoietin researched for tissue protection, nerve regeneration, and inflammatory pathways.",
    "longDescription": "ARA-290 is an 11-amino-acid peptide designed from the tertiary structure of erythropoietin (EPO). It specifically activates the innate repair receptor (IRR) without stimulating erythropoiesis, making it a critical tool for investigating neurological repair and inflammatory signal suppression.",
    "purity": "99.0%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 262.5,
    "casNumber": "1208243-50-8",
    "researchFocus": "Innate repair receptor activation and peripheral neuropathy pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/ara29-600x600.jpg"
  },
  {
    "id": "b7-33-2mg",
    "name": "B7-33 2mg",
    "category": "Tissue Regeneration Pathways",
    "description": "A synthetic peptide derived from relaxin researched for antifibrotic pathways and extracellular matrix remodeling.",
    "longDescription": "B7-33 is a functionally selective single-chain peptide modeled after the H2-relaxin hormone. It binds to the RXFP1 receptor with high affinity, activating antifibrotic signaling pathways and promoting collagen breakdown in fibroblast lines without raising risk of tumor growth.",
    "purity": "99.5%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 22.95,
    "casNumber": "115102-14-3 (Relaxin-modeled)",
    "researchFocus": "RXFP1 receptor activation and tissue fibrosis modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/b7-33a-small-600x600.jpg"
  },
  {
    "id": "b7-33-5mg",
    "name": "B7-33 5mg",
    "category": "Tissue Regeneration Pathways",
    "description": "A synthetic peptide derived from relaxin researched for antifibrotic pathways and extracellular matrix remodeling.",
    "longDescription": "B7-33 is a functionally selective single-chain peptide modeled after the H2-relaxin hormone. It binds to the RXFP1 receptor with high affinity, activating antifibrotic signaling pathways and promoting collagen breakdown in fibroblast lines without raising risk of tumor growth.",
    "purity": "99.5%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 34.42,
    "casNumber": "115102-14-3 (Relaxin-modeled)",
    "researchFocus": "RXFP1 receptor activation and tissue fibrosis modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/b7-33a-small-600x600.jpg"
  },
  {
    "id": "b7-33-10mg",
    "name": "B7-33 10mg",
    "category": "Tissue Regeneration Pathways",
    "description": "A synthetic peptide derived from relaxin researched for antifibrotic pathways and extracellular matrix remodeling.",
    "longDescription": "B7-33 is a functionally selective single-chain peptide modeled after the H2-relaxin hormone. It binds to the RXFP1 receptor with high affinity, activating antifibrotic signaling pathways and promoting collagen breakdown in fibroblast lines without raising risk of tumor growth.",
    "purity": "99.5%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 57.38,
    "casNumber": "115102-14-3 (Relaxin-modeled)",
    "researchFocus": "RXFP1 receptor activation and tissue fibrosis modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/b7-33a-small-600x600.jpg"
  },
  {
    "id": "b7-33-15mg",
    "name": "B7-33 15mg",
    "category": "Tissue Regeneration Pathways",
    "description": "A synthetic peptide derived from relaxin researched for antifibrotic pathways and extracellular matrix remodeling.",
    "longDescription": "B7-33 is a functionally selective single-chain peptide modeled after the H2-relaxin hormone. It binds to the RXFP1 receptor with high affinity, activating antifibrotic signaling pathways and promoting collagen breakdown in fibroblast lines without raising risk of tumor growth.",
    "purity": "99.5%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 80.33,
    "casNumber": "115102-14-3 (Relaxin-modeled)",
    "researchFocus": "RXFP1 receptor activation and tissue fibrosis modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/b7-33a-small-600x600.jpg"
  },
  {
    "id": "bronchogen-2mg",
    "name": "Bronchogen (Bioregulator Peptide) 2mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A short synthetic tetrapeptide researched for respiratory mucosal signaling and lung cell regeneration pathways.",
    "longDescription": "Bronchogen is a bioregulator peptide consisting of four amino acids (Ala-Glu-Asp-Leu) designed to interact with target lung tissues. In cellular longevity models, it is studied for its ability to regulate protein synthesis, influence telomerase activity, and maintain pulmonary cell line stability.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 39,
    "casNumber": "9002-60-3 (Respiratory-modeled)",
    "researchFocus": "Respiratory cell line preservation and telomerase regulation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Bronchogen%2020mg-600x600.png"
  },
  {
    "id": "bronchogen-5mg",
    "name": "Bronchogen (Bioregulator Peptide) 5mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A short synthetic tetrapeptide researched for respiratory mucosal signaling and lung cell regeneration pathways.",
    "longDescription": "Bronchogen is a bioregulator peptide consisting of four amino acids (Ala-Glu-Asp-Leu) designed to interact with target lung tissues. In cellular longevity models, it is studied for its ability to regulate protein synthesis, influence telomerase activity, and maintain pulmonary cell line stability.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 58.5,
    "casNumber": "9002-60-3 (Respiratory-modeled)",
    "researchFocus": "Respiratory cell line preservation and telomerase regulation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Bronchogen%2020mg-600x600.png"
  },
  {
    "id": "bronchogen-10mg",
    "name": "Bronchogen (Bioregulator Peptide) 10mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A short synthetic tetrapeptide researched for respiratory mucosal signaling and lung cell regeneration pathways.",
    "longDescription": "Bronchogen is a bioregulator peptide consisting of four amino acids (Ala-Glu-Asp-Leu) designed to interact with target lung tissues. In cellular longevity models, it is studied for its ability to regulate protein synthesis, influence telomerase activity, and maintain pulmonary cell line stability.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 97.5,
    "casNumber": "9002-60-3 (Respiratory-modeled)",
    "researchFocus": "Respiratory cell line preservation and telomerase regulation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Bronchogen%2020mg-600x600.png"
  },
  {
    "id": "bronchogen-15mg",
    "name": "Bronchogen (Bioregulator Peptide) 15mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A short synthetic tetrapeptide researched for respiratory mucosal signaling and lung cell regeneration pathways.",
    "longDescription": "Bronchogen is a bioregulator peptide consisting of four amino acids (Ala-Glu-Asp-Leu) designed to interact with target lung tissues. In cellular longevity models, it is studied for its ability to regulate protein synthesis, influence telomerase activity, and maintain pulmonary cell line stability.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 136.5,
    "casNumber": "9002-60-3 (Respiratory-modeled)",
    "researchFocus": "Respiratory cell line preservation and telomerase regulation",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Bronchogen%2020mg-600x600.png"
  },
  {
    "id": "cardiogen-2mg",
    "name": "Cardiogen (Bioregulator Peptide) 2mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A selective synthetic tetrapetide bioregulator studied for cardiovascular cell regeneration and fibroblast proliferation.",
    "longDescription": "Cardiogen is a short peptide bioregulator with the sequence Ala-Glu-Asp-Arg. It is studied in cardiac cell biology for its role in supporting myocardial tissue health, regulating fibroblast proliferation, and preserving cellular lifespan under hypoxic stress models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 49,
    "casNumber": "947303-05-7",
    "researchFocus": "Myocardial cell protection and fibrotic signal suppression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/cardiogen-600x600.jpg"
  },
  {
    "id": "cardiogen-5mg",
    "name": "Cardiogen (Bioregulator Peptide) 5mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A selective synthetic tetrapetide bioregulator studied for cardiovascular cell regeneration and fibroblast proliferation.",
    "longDescription": "Cardiogen is a short peptide bioregulator with the sequence Ala-Glu-Asp-Arg. It is studied in cardiac cell biology for its role in supporting myocardial tissue health, regulating fibroblast proliferation, and preserving cellular lifespan under hypoxic stress models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 73.5,
    "casNumber": "947303-05-7",
    "researchFocus": "Myocardial cell protection and fibrotic signal suppression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/cardiogen-600x600.jpg"
  },
  {
    "id": "cardiogen-10mg",
    "name": "Cardiogen (Bioregulator Peptide) 10mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A selective synthetic tetrapetide bioregulator studied for cardiovascular cell regeneration and fibroblast proliferation.",
    "longDescription": "Cardiogen is a short peptide bioregulator with the sequence Ala-Glu-Asp-Arg. It is studied in cardiac cell biology for its role in supporting myocardial tissue health, regulating fibroblast proliferation, and preserving cellular lifespan under hypoxic stress models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 122.5,
    "casNumber": "947303-05-7",
    "researchFocus": "Myocardial cell protection and fibrotic signal suppression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/cardiogen-600x600.jpg"
  },
  {
    "id": "cardiogen-15mg",
    "name": "Cardiogen (Bioregulator Peptide) 15mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A selective synthetic tetrapetide bioregulator studied for cardiovascular cell regeneration and fibroblast proliferation.",
    "longDescription": "Cardiogen is a short peptide bioregulator with the sequence Ala-Glu-Asp-Arg. It is studied in cardiac cell biology for its role in supporting myocardial tissue health, regulating fibroblast proliferation, and preserving cellular lifespan under hypoxic stress models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 171.5,
    "casNumber": "947303-05-7",
    "researchFocus": "Myocardial cell protection and fibrotic signal suppression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/cardiogen-600x600.jpg"
  },
  {
    "id": "cartalax-2mg",
    "name": "Cartalax (Bioregulator Peptide) 2mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic peptide bioregulator studied for cartilage tissue regulation and chondrocyte health.",
    "longDescription": "Cartalax is a tripeptide (Ala-Glu-Asp) researched in rheumatology and gerontology models. It acts as a cartilage bioregulator, stimulating proteoglycan synthesis in chondrocyte cultures and investigating joint matrix durability pathways.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 49,
    "casNumber": "9002-60-4 (Chondro-modeled)",
    "researchFocus": "Chondrocyte regeneration and extracellular joint matrix modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Cartalax-20mg-600x600.png"
  },
  {
    "id": "cartalax-5mg",
    "name": "Cartalax (Bioregulator Peptide) 5mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic peptide bioregulator studied for cartilage tissue regulation and chondrocyte health.",
    "longDescription": "Cartalax is a tripeptide (Ala-Glu-Asp) researched in rheumatology and gerontology models. It acts as a cartilage bioregulator, stimulating proteoglycan synthesis in chondrocyte cultures and investigating joint matrix durability pathways.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 73.5,
    "casNumber": "9002-60-4 (Chondro-modeled)",
    "researchFocus": "Chondrocyte regeneration and extracellular joint matrix modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Cartalax-20mg-600x600.png"
  },
  {
    "id": "cartalax-10mg",
    "name": "Cartalax (Bioregulator Peptide) 10mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic peptide bioregulator studied for cartilage tissue regulation and chondrocyte health.",
    "longDescription": "Cartalax is a tripeptide (Ala-Glu-Asp) researched in rheumatology and gerontology models. It acts as a cartilage bioregulator, stimulating proteoglycan synthesis in chondrocyte cultures and investigating joint matrix durability pathways.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 122.5,
    "casNumber": "9002-60-4 (Chondro-modeled)",
    "researchFocus": "Chondrocyte regeneration and extracellular joint matrix modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Cartalax-20mg-600x600.png"
  },
  {
    "id": "cartalax-15mg",
    "name": "Cartalax (Bioregulator Peptide) 15mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic peptide bioregulator studied for cartilage tissue regulation and chondrocyte health.",
    "longDescription": "Cartalax is a tripeptide (Ala-Glu-Asp) researched in rheumatology and gerontology models. It acts as a cartilage bioregulator, stimulating proteoglycan synthesis in chondrocyte cultures and investigating joint matrix durability pathways.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 171.5,
    "casNumber": "9002-60-4 (Chondro-modeled)",
    "researchFocus": "Chondrocyte regeneration and extracellular joint matrix modeling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Cartalax-20mg-600x600.png"
  },
  {
    "id": "cjc-1295-2mg",
    "name": "CJC-1295 with DAC 2mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic GHRH analogue conjugated with Drug Affinity Complex (DAC) researched for extended somatotropic pathway signaling.",
    "longDescription": "CJC-1295 with DAC is a synthetic 30-amino-acid peptide that incorporates a Drug Affinity Complex (DAC) to covalently bind to endogenous albumin. This conjugation dramatically extends the biological presence of GHRH in in-vitro assays, permitting deep study of long-term somatropic receptor affinity.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 22,
    "casNumber": "863288-34-0",
    "researchFocus": "Albumin-conjugated receptor affinity and extended GHRH signaling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/CJC-1295-DAC-600x600.png"
  },
  {
    "id": "cjc-1295-5mg",
    "name": "CJC-1295 with DAC 5mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic GHRH analogue conjugated with Drug Affinity Complex (DAC) researched for extended somatotropic pathway signaling.",
    "longDescription": "CJC-1295 with DAC is a synthetic 30-amino-acid peptide that incorporates a Drug Affinity Complex (DAC) to covalently bind to endogenous albumin. This conjugation dramatically extends the biological presence of GHRH in in-vitro assays, permitting deep study of long-term somatropic receptor affinity.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 33,
    "casNumber": "863288-34-0",
    "researchFocus": "Albumin-conjugated receptor affinity and extended GHRH signaling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/CJC-1295-DAC-600x600.png"
  },
  {
    "id": "cjc-1295-10mg",
    "name": "CJC-1295 with DAC 10mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic GHRH analogue conjugated with Drug Affinity Complex (DAC) researched for extended somatotropic pathway signaling.",
    "longDescription": "CJC-1295 with DAC is a synthetic 30-amino-acid peptide that incorporates a Drug Affinity Complex (DAC) to covalently bind to endogenous albumin. This conjugation dramatically extends the biological presence of GHRH in in-vitro assays, permitting deep study of long-term somatropic receptor affinity.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 55,
    "casNumber": "863288-34-0",
    "researchFocus": "Albumin-conjugated receptor affinity and extended GHRH signaling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/CJC-1295-DAC-600x600.png"
  },
  {
    "id": "cjc-1295-15mg",
    "name": "CJC-1295 with DAC 15mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic GHRH analogue conjugated with Drug Affinity Complex (DAC) researched for extended somatotropic pathway signaling.",
    "longDescription": "CJC-1295 with DAC is a synthetic 30-amino-acid peptide that incorporates a Drug Affinity Complex (DAC) to covalently bind to endogenous albumin. This conjugation dramatically extends the biological presence of GHRH in in-vitro assays, permitting deep study of long-term somatropic receptor affinity.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 77,
    "casNumber": "863288-34-0",
    "researchFocus": "Albumin-conjugated receptor affinity and extended GHRH signaling",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/CJC-1295-DAC-600x600.png"
  },
  {
    "id": "colivelin-2mg",
    "name": "Colivelin 2mg",
    "category": "Neurological & Cognitive Research",
    "description": "A highly potent neuroprotective peptide fragment of Humanin studied for axonal survival and cognitive disease modeling.",
    "longDescription": "Colivelin is a synthetic hybrid peptide composed of activity-dependent neurotrophic factor (ADNF) and Humanin. It operates as a potent activator of STAT3, researched in neurodegenerative models for its powerful anti-apoptotic activity and ability to rescue cells from beta-amyloid toxicity.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 28,
    "casNumber": "867021-83-8",
    "researchFocus": "STAT3 activation, axonal survival, and amyloid toxicity protection",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/colivelin-600x600.jpg"
  },
  {
    "id": "colivelin-5mg",
    "name": "Colivelin 5mg",
    "category": "Neurological & Cognitive Research",
    "description": "A highly potent neuroprotective peptide fragment of Humanin studied for axonal survival and cognitive disease modeling.",
    "longDescription": "Colivelin is a synthetic hybrid peptide composed of activity-dependent neurotrophic factor (ADNF) and Humanin. It operates as a potent activator of STAT3, researched in neurodegenerative models for its powerful anti-apoptotic activity and ability to rescue cells from beta-amyloid toxicity.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 41.99,
    "casNumber": "867021-83-8",
    "researchFocus": "STAT3 activation, axonal survival, and amyloid toxicity protection",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/colivelin-600x600.jpg"
  },
  {
    "id": "colivelin-10mg",
    "name": "Colivelin 10mg",
    "category": "Neurological & Cognitive Research",
    "description": "A highly potent neuroprotective peptide fragment of Humanin studied for axonal survival and cognitive disease modeling.",
    "longDescription": "Colivelin is a synthetic hybrid peptide composed of activity-dependent neurotrophic factor (ADNF) and Humanin. It operates as a potent activator of STAT3, researched in neurodegenerative models for its powerful anti-apoptotic activity and ability to rescue cells from beta-amyloid toxicity.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 69.99,
    "casNumber": "867021-83-8",
    "researchFocus": "STAT3 activation, axonal survival, and amyloid toxicity protection",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/colivelin-600x600.jpg"
  },
  {
    "id": "colivelin-15mg",
    "name": "Colivelin 15mg",
    "category": "Neurological & Cognitive Research",
    "description": "A highly potent neuroprotective peptide fragment of Humanin studied for axonal survival and cognitive disease modeling.",
    "longDescription": "Colivelin is a synthetic hybrid peptide composed of activity-dependent neurotrophic factor (ADNF) and Humanin. It operates as a potent activator of STAT3, researched in neurodegenerative models for its powerful anti-apoptotic activity and ability to rescue cells from beta-amyloid toxicity.",
    "purity": "99.3%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 97.99,
    "casNumber": "867021-83-8",
    "researchFocus": "STAT3 activation, axonal survival, and amyloid toxicity protection",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/colivelin-600x600.jpg"
  },
  {
    "id": "cortagen-2mg",
    "name": "Cortagen (Bioregulator Peptide) 2mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic tetrapeptide derived from Cortexin studied for brain tissue modeling and neural cell regeneration.",
    "longDescription": "Cortagen is a synthetic short bioregulator peptide with the sequence Ala-Glu-Asp-Pro. It has high specificity for central nervous system tissues, researched extensively for its influence on gene expression in neural stem cells, neuroprotective signaling, and cell-division cycles.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 49,
    "casNumber": "947303-05-8",
    "researchFocus": "Cerebral cell regeneration, stem cell differentiation, and gene expression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/Cortagen-600x600.jpg"
  },
  {
    "id": "cortagen-5mg",
    "name": "Cortagen (Bioregulator Peptide) 5mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic tetrapeptide derived from Cortexin studied for brain tissue modeling and neural cell regeneration.",
    "longDescription": "Cortagen is a synthetic short bioregulator peptide with the sequence Ala-Glu-Asp-Pro. It has high specificity for central nervous system tissues, researched extensively for its influence on gene expression in neural stem cells, neuroprotective signaling, and cell-division cycles.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 73.5,
    "casNumber": "947303-05-8",
    "researchFocus": "Cerebral cell regeneration, stem cell differentiation, and gene expression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/Cortagen-600x600.jpg"
  },
  {
    "id": "cortagen-10mg",
    "name": "Cortagen (Bioregulator Peptide) 10mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic tetrapeptide derived from Cortexin studied for brain tissue modeling and neural cell regeneration.",
    "longDescription": "Cortagen is a synthetic short bioregulator peptide with the sequence Ala-Glu-Asp-Pro. It has high specificity for central nervous system tissues, researched extensively for its influence on gene expression in neural stem cells, neuroprotective signaling, and cell-division cycles.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 122.5,
    "casNumber": "947303-05-8",
    "researchFocus": "Cerebral cell regeneration, stem cell differentiation, and gene expression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/Cortagen-600x600.jpg"
  },
  {
    "id": "cortagen-15mg",
    "name": "Cortagen (Bioregulator Peptide) 15mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic tetrapeptide derived from Cortexin studied for brain tissue modeling and neural cell regeneration.",
    "longDescription": "Cortagen is a synthetic short bioregulator peptide with the sequence Ala-Glu-Asp-Pro. It has high specificity for central nervous system tissues, researched extensively for its influence on gene expression in neural stem cells, neuroprotective signaling, and cell-division cycles.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 171.5,
    "casNumber": "947303-05-8",
    "researchFocus": "Cerebral cell regeneration, stem cell differentiation, and gene expression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/Cortagen-600x600.jpg"
  },
  {
    "id": "crystagen-2mg",
    "name": "Crystagen (Bioregulator Peptide) 2mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic bioregulator peptide researched for immune system cell health and lymphocyte regulation.",
    "longDescription": "Crystagen is a synthetic peptide bioregulator with the sequence Ala-Glu-Asp. It interacts selectively with immune system tissues, researched in immunology and gerontology for its potential to stimulate lymphocyte protein synthesis and restore immunogenesis profiles in aging cellular models.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 59,
    "casNumber": "9002-60-5 (Immune-modeled)",
    "researchFocus": "Lymphocyte protein synthesis and immunogenesis kinetics",
    "image": "https://www.uk-peptides.com/image/cache/catalog/crystagen-600x600.jpg"
  },
  {
    "id": "crystagen-5mg",
    "name": "Crystagen (Bioregulator Peptide) 5mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic bioregulator peptide researched for immune system cell health and lymphocyte regulation.",
    "longDescription": "Crystagen is a synthetic peptide bioregulator with the sequence Ala-Glu-Asp. It interacts selectively with immune system tissues, researched in immunology and gerontology for its potential to stimulate lymphocyte protein synthesis and restore immunogenesis profiles in aging cellular models.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 88.5,
    "casNumber": "9002-60-5 (Immune-modeled)",
    "researchFocus": "Lymphocyte protein synthesis and immunogenesis kinetics",
    "image": "https://www.uk-peptides.com/image/cache/catalog/crystagen-600x600.jpg"
  },
  {
    "id": "crystagen-10mg",
    "name": "Crystagen (Bioregulator Peptide) 10mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic bioregulator peptide researched for immune system cell health and lymphocyte regulation.",
    "longDescription": "Crystagen is a synthetic peptide bioregulator with the sequence Ala-Glu-Asp. It interacts selectively with immune system tissues, researched in immunology and gerontology for its potential to stimulate lymphocyte protein synthesis and restore immunogenesis profiles in aging cellular models.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 147.5,
    "casNumber": "9002-60-5 (Immune-modeled)",
    "researchFocus": "Lymphocyte protein synthesis and immunogenesis kinetics",
    "image": "https://www.uk-peptides.com/image/cache/catalog/crystagen-600x600.jpg"
  },
  {
    "id": "crystagen-15mg",
    "name": "Crystagen (Bioregulator Peptide) 15mg",
    "category": "Cellular Longevity & Telomeres",
    "description": "A synthetic bioregulator peptide researched for immune system cell health and lymphocyte regulation.",
    "longDescription": "Crystagen is a synthetic peptide bioregulator with the sequence Ala-Glu-Asp. It interacts selectively with immune system tissues, researched in immunology and gerontology for its potential to stimulate lymphocyte protein synthesis and restore immunogenesis profiles in aging cellular models.",
    "purity": "99.4%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 206.5,
    "casNumber": "9002-60-5 (Immune-modeled)",
    "researchFocus": "Lymphocyte protein synthesis and immunogenesis kinetics",
    "image": "https://www.uk-peptides.com/image/cache/catalog/crystagen-600x600.jpg"
  },
  {
    "id": "dermorphin-2mg",
    "name": "Dermorphin 2mg",
    "category": "Neurological & Cognitive Research",
    "description": "A naturally occurring mu-opioid receptor agonist peptide first isolated from South American frog skin.",
    "longDescription": "Dermorphin is a heptapeptide originally isolated from the skin of Phyllomedusa frogs. It is a highly studied, selective agonist for the mu-opioid receptor, utilized in pain pathway research, neuroreceptor localization, and neurotransmitter signaling assays.",
    "purity": "98.9%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 29,
    "casNumber": "77614-16-5",
    "researchFocus": "Mu-opioid receptor localization and pain pathway mapping",
    "image": "https://www.uk-peptides.com/image/cache/catalog/dermorphin-small-600x600.png"
  },
  {
    "id": "dermorphin-5mg",
    "name": "Dermorphin 5mg",
    "category": "Neurological & Cognitive Research",
    "description": "A naturally occurring mu-opioid receptor agonist peptide first isolated from South American frog skin.",
    "longDescription": "Dermorphin is a heptapeptide originally isolated from the skin of Phyllomedusa frogs. It is a highly studied, selective agonist for the mu-opioid receptor, utilized in pain pathway research, neuroreceptor localization, and neurotransmitter signaling assays.",
    "purity": "98.9%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 43.5,
    "casNumber": "77614-16-5",
    "researchFocus": "Mu-opioid receptor localization and pain pathway mapping",
    "image": "https://www.uk-peptides.com/image/cache/catalog/dermorphin-small-600x600.png"
  },
  {
    "id": "dermorphin-10mg",
    "name": "Dermorphin 10mg",
    "category": "Neurological & Cognitive Research",
    "description": "A naturally occurring mu-opioid receptor agonist peptide first isolated from South American frog skin.",
    "longDescription": "Dermorphin is a heptapeptide originally isolated from the skin of Phyllomedusa frogs. It is a highly studied, selective agonist for the mu-opioid receptor, utilized in pain pathway research, neuroreceptor localization, and neurotransmitter signaling assays.",
    "purity": "98.9%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 72.5,
    "casNumber": "77614-16-5",
    "researchFocus": "Mu-opioid receptor localization and pain pathway mapping",
    "image": "https://www.uk-peptides.com/image/cache/catalog/dermorphin-small-600x600.png"
  },
  {
    "id": "dermorphin-15mg",
    "name": "Dermorphin 15mg",
    "category": "Neurological & Cognitive Research",
    "description": "A naturally occurring mu-opioid receptor agonist peptide first isolated from South American frog skin.",
    "longDescription": "Dermorphin is a heptapeptide originally isolated from the skin of Phyllomedusa frogs. It is a highly studied, selective agonist for the mu-opioid receptor, utilized in pain pathway research, neuroreceptor localization, and neurotransmitter signaling assays.",
    "purity": "98.9%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 101.5,
    "casNumber": "77614-16-5",
    "researchFocus": "Mu-opioid receptor localization and pain pathway mapping",
    "image": "https://www.uk-peptides.com/image/cache/catalog/dermorphin-small-600x600.png"
  },
  {
    "id": "dihexa-2mg",
    "name": "Dihexa 2mg",
    "category": "Neurological & Cognitive Research",
    "description": "An oligopeptide drug candidate derived from angiotensin IV researched for synaptic connection growth and HGF activation.",
    "longDescription": "Dihexa is a high-potency oligopeptide derived from Angiotensin IV. It exhibits high binding affinity to Hepatocyte Growth Factor (HGF), promoting spinogenesis and synaptogenesis in hippocampal neurons. It is a vital tool for studying synapse formation and neurological rejuvenation cascades.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 23.6,
    "casNumber": "1401708-83-5",
    "researchFocus": "HGF pathway activation, spinogenesis, and hippocampal neuron growth",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Dihexa-600x600.png"
  },
  {
    "id": "dihexa-5mg",
    "name": "Dihexa 5mg",
    "category": "Neurological & Cognitive Research",
    "description": "An oligopeptide drug candidate derived from angiotensin IV researched for synaptic connection growth and HGF activation.",
    "longDescription": "Dihexa is a high-potency oligopeptide derived from Angiotensin IV. It exhibits high binding affinity to Hepatocyte Growth Factor (HGF), promoting spinogenesis and synaptogenesis in hippocampal neurons. It is a vital tool for studying synapse formation and neurological rejuvenation cascades.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 35.4,
    "casNumber": "1401708-83-5",
    "researchFocus": "HGF pathway activation, spinogenesis, and hippocampal neuron growth",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Dihexa-600x600.png"
  },
  {
    "id": "dihexa-10mg",
    "name": "Dihexa 10mg",
    "category": "Neurological & Cognitive Research",
    "description": "An oligopeptide drug candidate derived from angiotensin IV researched for synaptic connection growth and HGF activation.",
    "longDescription": "Dihexa is a high-potency oligopeptide derived from Angiotensin IV. It exhibits high binding affinity to Hepatocyte Growth Factor (HGF), promoting spinogenesis and synaptogenesis in hippocampal neurons. It is a vital tool for studying synapse formation and neurological rejuvenation cascades.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 59,
    "casNumber": "1401708-83-5",
    "researchFocus": "HGF pathway activation, spinogenesis, and hippocampal neuron growth",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Dihexa-600x600.png"
  },
  {
    "id": "dihexa-15mg",
    "name": "Dihexa 15mg",
    "category": "Neurological & Cognitive Research",
    "description": "An oligopeptide drug candidate derived from angiotensin IV researched for synaptic connection growth and HGF activation.",
    "longDescription": "Dihexa is a high-potency oligopeptide derived from Angiotensin IV. It exhibits high binding affinity to Hepatocyte Growth Factor (HGF), promoting spinogenesis and synaptogenesis in hippocampal neurons. It is a vital tool for studying synapse formation and neurological rejuvenation cascades.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 82.6,
    "casNumber": "1401708-83-5",
    "researchFocus": "HGF pathway activation, spinogenesis, and hippocampal neuron growth",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/Dihexa-600x600.png"
  },
  {
    "id": "dnsp-11-2mg",
    "name": "DNSP-11 2mg",
    "category": "Neurological & Cognitive Research",
    "description": "A dopamine neuron stimulating peptide studied for neuroprotective mechanisms and glial-derived neurotrophic pathways.",
    "longDescription": "Dopamine Neuron Stimulating Peptide-11 (DNSP-11) is an 11-amino-acid peptide derived from glial-derived neurotrophic factor (GDNF). It has been shown in in-vitro models to exhibit potent neuroprotective activity, protecting dopaminergic cells from oxidative stress and maintaining synaptic survival.",
    "purity": "99.0%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 50,
    "casNumber": "1055008-36-8",
    "researchFocus": "Dopaminergic cell preservation and glial-derived survival pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/DNSP11-600x600.jpg"
  },
  {
    "id": "dnsp-11-5mg",
    "name": "DNSP-11 5mg",
    "category": "Neurological & Cognitive Research",
    "description": "A dopamine neuron stimulating peptide studied for neuroprotective mechanisms and glial-derived neurotrophic pathways.",
    "longDescription": "Dopamine Neuron Stimulating Peptide-11 (DNSP-11) is an 11-amino-acid peptide derived from glial-derived neurotrophic factor (GDNF). It has been shown in in-vitro models to exhibit potent neuroprotective activity, protecting dopaminergic cells from oxidative stress and maintaining synaptic survival.",
    "purity": "99.0%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 75,
    "casNumber": "1055008-36-8",
    "researchFocus": "Dopaminergic cell preservation and glial-derived survival pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/DNSP11-600x600.jpg"
  },
  {
    "id": "dnsp-11-10mg",
    "name": "DNSP-11 10mg",
    "category": "Neurological & Cognitive Research",
    "description": "A dopamine neuron stimulating peptide studied for neuroprotective mechanisms and glial-derived neurotrophic pathways.",
    "longDescription": "Dopamine Neuron Stimulating Peptide-11 (DNSP-11) is an 11-amino-acid peptide derived from glial-derived neurotrophic factor (GDNF). It has been shown in in-vitro models to exhibit potent neuroprotective activity, protecting dopaminergic cells from oxidative stress and maintaining synaptic survival.",
    "purity": "99.0%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 125,
    "casNumber": "1055008-36-8",
    "researchFocus": "Dopaminergic cell preservation and glial-derived survival pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/DNSP11-600x600.jpg"
  },
  {
    "id": "dnsp-11-15mg",
    "name": "DNSP-11 15mg",
    "category": "Neurological & Cognitive Research",
    "description": "A dopamine neuron stimulating peptide studied for neuroprotective mechanisms and glial-derived neurotrophic pathways.",
    "longDescription": "Dopamine Neuron Stimulating Peptide-11 (DNSP-11) is an 11-amino-acid peptide derived from glial-derived neurotrophic factor (GDNF). It has been shown in in-vitro models to exhibit potent neuroprotective activity, protecting dopaminergic cells from oxidative stress and maintaining synaptic survival.",
    "purity": "99.0%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 175,
    "casNumber": "1055008-36-8",
    "researchFocus": "Dopaminergic cell preservation and glial-derived survival pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/DNSP11-600x600.jpg"
  },
  {
    "id": "dsip-2mg",
    "name": "DSIP (Delta Sleep-Inducing Peptide) 2mg",
    "category": "Neurological & Cognitive Research",
    "description": "A naturally occurring somnogenic peptide studied for circadian rhythm regulation and stress-mitigation pathways.",
    "longDescription": "Delta Sleep-Inducing Peptide (DSIP) is a naturally occurring nonapeptide first isolated from rabbit brain tissue. It is researched extensively for its neuromodulatory role, regulating sleep-wake cycles, circadian rhythm signaling, and pituitary hormone release, as well as protecting cells from stress-induced oxidation.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 9.3,
    "casNumber": "62568-57-4",
    "researchFocus": "Circadian rhythm signaling and stress-induced oxidation protection",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/DSIP-600x600.png"
  },
  {
    "id": "dsip-5mg",
    "name": "DSIP (Delta Sleep-Inducing Peptide) 5mg",
    "category": "Neurological & Cognitive Research",
    "description": "A naturally occurring somnogenic peptide studied for circadian rhythm regulation and stress-mitigation pathways.",
    "longDescription": "Delta Sleep-Inducing Peptide (DSIP) is a naturally occurring nonapeptide first isolated from rabbit brain tissue. It is researched extensively for its neuromodulatory role, regulating sleep-wake cycles, circadian rhythm signaling, and pituitary hormone release, as well as protecting cells from stress-induced oxidation.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 13.95,
    "casNumber": "62568-57-4",
    "researchFocus": "Circadian rhythm signaling and stress-induced oxidation protection",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/DSIP-600x600.png"
  },
  {
    "id": "dsip-10mg",
    "name": "DSIP (Delta Sleep-Inducing Peptide) 10mg",
    "category": "Neurological & Cognitive Research",
    "description": "A naturally occurring somnogenic peptide studied for circadian rhythm regulation and stress-mitigation pathways.",
    "longDescription": "Delta Sleep-Inducing Peptide (DSIP) is a naturally occurring nonapeptide first isolated from rabbit brain tissue. It is researched extensively for its neuromodulatory role, regulating sleep-wake cycles, circadian rhythm signaling, and pituitary hormone release, as well as protecting cells from stress-induced oxidation.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 23.25,
    "casNumber": "62568-57-4",
    "researchFocus": "Circadian rhythm signaling and stress-induced oxidation protection",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/DSIP-600x600.png"
  },
  {
    "id": "dsip-15mg",
    "name": "DSIP (Delta Sleep-Inducing Peptide) 15mg",
    "category": "Neurological & Cognitive Research",
    "description": "A naturally occurring somnogenic peptide studied for circadian rhythm regulation and stress-mitigation pathways.",
    "longDescription": "Delta Sleep-Inducing Peptide (DSIP) is a naturally occurring nonapeptide first isolated from rabbit brain tissue. It is researched extensively for its neuromodulatory role, regulating sleep-wake cycles, circadian rhythm signaling, and pituitary hormone release, as well as protecting cells from stress-induced oxidation.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 32.55,
    "casNumber": "62568-57-4",
    "researchFocus": "Circadian rhythm signaling and stress-induced oxidation protection",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/DSIP-600x600.png"
  },
  {
    "id": "ghk-cu-2mg",
    "name": "GHK-Cu (Copper Peptide) 2mg",
    "category": "Extracellular Matrix Modeling",
    "description": "A high-yielding tripeptide-copper complex widely researched for collagen synthesis, dermal remodeling, and cellular protection.",
    "longDescription": "GHK-Cu is a naturally occurring tripeptide (glycyl-L-histidyl-L-lysine) with a high affinity for copper ions. It is a highly studied regulator of dermal tissue remodeling, stimulating collagen, dermatan sulfate, chondroitin sulfate, and decorin synthesis in fibroblast cultures.",
    "purity": "98.8%",
    "formulation": "Lyophilised Blue Powder",
    "size": "2mg",
    "price": 26.99,
    "casNumber": "49557-75-7",
    "researchFocus": "Fibroblast activation, collagen matrix repair, and gene expression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHK-CU-50mg-600x600.jpg"
  },
  {
    "id": "ghk-cu-5mg",
    "name": "GHK-Cu (Copper Peptide) 5mg",
    "category": "Extracellular Matrix Modeling",
    "description": "A high-yielding tripeptide-copper complex widely researched for collagen synthesis, dermal remodeling, and cellular protection.",
    "longDescription": "GHK-Cu is a naturally occurring tripeptide (glycyl-L-histidyl-L-lysine) with a high affinity for copper ions. It is a highly studied regulator of dermal tissue remodeling, stimulating collagen, dermatan sulfate, chondroitin sulfate, and decorin synthesis in fibroblast cultures.",
    "purity": "98.8%",
    "formulation": "Lyophilised Blue Powder",
    "size": "5mg",
    "price": 40.48,
    "casNumber": "49557-75-7",
    "researchFocus": "Fibroblast activation, collagen matrix repair, and gene expression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHK-CU-50mg-600x600.jpg"
  },
  {
    "id": "ghk-cu-10mg",
    "name": "GHK-Cu (Copper Peptide) 10mg",
    "category": "Extracellular Matrix Modeling",
    "description": "A high-yielding tripeptide-copper complex widely researched for collagen synthesis, dermal remodeling, and cellular protection.",
    "longDescription": "GHK-Cu is a naturally occurring tripeptide (glycyl-L-histidyl-L-lysine) with a high affinity for copper ions. It is a highly studied regulator of dermal tissue remodeling, stimulating collagen, dermatan sulfate, chondroitin sulfate, and decorin synthesis in fibroblast cultures.",
    "purity": "98.8%",
    "formulation": "Lyophilised Blue Powder",
    "size": "10mg",
    "price": 67.47,
    "casNumber": "49557-75-7",
    "researchFocus": "Fibroblast activation, collagen matrix repair, and gene expression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHK-CU-50mg-600x600.jpg"
  },
  {
    "id": "ghk-cu-15mg",
    "name": "GHK-Cu (Copper Peptide) 15mg",
    "category": "Extracellular Matrix Modeling",
    "description": "A high-yielding tripeptide-copper complex widely researched for collagen synthesis, dermal remodeling, and cellular protection.",
    "longDescription": "GHK-Cu is a naturally occurring tripeptide (glycyl-L-histidyl-L-lysine) with a high affinity for copper ions. It is a highly studied regulator of dermal tissue remodeling, stimulating collagen, dermatan sulfate, chondroitin sulfate, and decorin synthesis in fibroblast cultures.",
    "purity": "98.8%",
    "formulation": "Lyophilised Blue Powder",
    "size": "15mg",
    "price": 94.46,
    "casNumber": "49557-75-7",
    "researchFocus": "Fibroblast activation, collagen matrix repair, and gene expression",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/GHK-CU-50mg-600x600.jpg"
  },
  {
    "id": "pt-141-2mg",
    "name": "PT-141 (Bremelanotide) 2mg",
    "category": "Melanogenesis Pathways",
    "description": "A cyclic peptide analogue of alpha-MSH studied for melanocortin receptor affinity and neuroreceptor pathways.",
    "longDescription": "PT-141 (Bremelanotide) is a synthetic cyclic peptide designed as an analogue of alpha-melanocyte-stimulating hormone (a-MSH). It binds to MC3 and MC4 melanocortin receptors, facilitating neuroscience research into metabolic responses, signaling mechanisms, and central neuroreceptor pathways.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 8.4,
    "casNumber": "189691-06-3",
    "researchFocus": "MC3/MC4 melanocortin receptor activation and autonomic signaling pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/PT-141-600x600.png"
  },
  {
    "id": "pt-141-5mg",
    "name": "PT-141 (Bremelanotide) 5mg",
    "category": "Melanogenesis Pathways",
    "description": "A cyclic peptide analogue of alpha-MSH studied for melanocortin receptor affinity and neuroreceptor pathways.",
    "longDescription": "PT-141 (Bremelanotide) is a synthetic cyclic peptide designed as an analogue of alpha-melanocyte-stimulating hormone (a-MSH). It binds to MC3 and MC4 melanocortin receptors, facilitating neuroscience research into metabolic responses, signaling mechanisms, and central neuroreceptor pathways.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 12.6,
    "casNumber": "189691-06-3",
    "researchFocus": "MC3/MC4 melanocortin receptor activation and autonomic signaling pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/PT-141-600x600.png"
  },
  {
    "id": "pt-141-10mg",
    "name": "PT-141 (Bremelanotide) 10mg",
    "category": "Melanogenesis Pathways",
    "description": "A cyclic peptide analogue of alpha-MSH studied for melanocortin receptor affinity and neuroreceptor pathways.",
    "longDescription": "PT-141 (Bremelanotide) is a synthetic cyclic peptide designed as an analogue of alpha-melanocyte-stimulating hormone (a-MSH). It binds to MC3 and MC4 melanocortin receptors, facilitating neuroscience research into metabolic responses, signaling mechanisms, and central neuroreceptor pathways.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 21,
    "casNumber": "189691-06-3",
    "researchFocus": "MC3/MC4 melanocortin receptor activation and autonomic signaling pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/PT-141-600x600.png"
  },
  {
    "id": "pt-141-15mg",
    "name": "PT-141 (Bremelanotide) 15mg",
    "category": "Melanogenesis Pathways",
    "description": "A cyclic peptide analogue of alpha-MSH studied for melanocortin receptor affinity and neuroreceptor pathways.",
    "longDescription": "PT-141 (Bremelanotide) is a synthetic cyclic peptide designed as an analogue of alpha-melanocyte-stimulating hormone (a-MSH). It binds to MC3 and MC4 melanocortin receptors, facilitating neuroscience research into metabolic responses, signaling mechanisms, and central neuroreceptor pathways.",
    "purity": "99.2%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 29.4,
    "casNumber": "189691-06-3",
    "researchFocus": "MC3/MC4 melanocortin receptor activation and autonomic signaling pathways",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/PT-141-600x600.png"
  },
  {
    "id": "tesamorelin-2mg",
    "name": "Tesamorelin 2mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic growth hormone-releasing hormone (GHRH) analog studied for adipose tissue reduction and metabolic modeling.",
    "longDescription": "Tesamorelin is a synthetic peptide analog of Growth Hormone-Releasing Hormone (GHRH). It is stabilized with a hexenoyl group to enhance biological resilience. It is highly studied for its lipolytic properties, especially in reducing visceral adipose tissue and improving metabolic profiles in in-vitro biological models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "2mg",
    "price": 29,
    "casNumber": "901758-09-6",
    "researchFocus": "Metabolic modeling and growth hormone secretagogue activity",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/tesamorelin-600x600.png"
  },
  {
    "id": "tesamorelin-5mg",
    "name": "Tesamorelin 5mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic growth hormone-releasing hormone (GHRH) analog studied for adipose tissue reduction and metabolic modeling.",
    "longDescription": "Tesamorelin is a synthetic peptide analog of Growth Hormone-Releasing Hormone (GHRH). It is stabilized with a hexenoyl group to enhance biological resilience. It is highly studied for its lipolytic properties, especially in reducing visceral adipose tissue and improving metabolic profiles in in-vitro biological models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "5mg",
    "price": 43.5,
    "casNumber": "901758-09-6",
    "researchFocus": "Metabolic modeling and growth hormone secretagogue activity",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/tesamorelin-600x600.png"
  },
  {
    "id": "tesamorelin-10mg",
    "name": "Tesamorelin 10mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic growth hormone-releasing hormone (GHRH) analog studied for adipose tissue reduction and metabolic modeling.",
    "longDescription": "Tesamorelin is a synthetic peptide analog of Growth Hormone-Releasing Hormone (GHRH). It is stabilized with a hexenoyl group to enhance biological resilience. It is highly studied for its lipolytic properties, especially in reducing visceral adipose tissue and improving metabolic profiles in in-vitro biological models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "10mg",
    "price": 72.5,
    "casNumber": "901758-09-6",
    "researchFocus": "Metabolic modeling and growth hormone secretagogue activity",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/tesamorelin-600x600.png"
  },
  {
    "id": "tesamorelin-15mg",
    "name": "Tesamorelin 15mg",
    "category": "Growth Hormone Signaling",
    "description": "A synthetic growth hormone-releasing hormone (GHRH) analog studied for adipose tissue reduction and metabolic modeling.",
    "longDescription": "Tesamorelin is a synthetic peptide analog of Growth Hormone-Releasing Hormone (GHRH). It is stabilized with a hexenoyl group to enhance biological resilience. It is highly studied for its lipolytic properties, especially in reducing visceral adipose tissue and improving metabolic profiles in in-vitro biological models.",
    "purity": "99.1%",
    "formulation": "Lyophilised White Powder",
    "size": "15mg",
    "price": 101.5,
    "casNumber": "901758-09-6",
    "researchFocus": "Metabolic modeling and growth hormone secretagogue activity",
    "image": "https://www.uk-peptides.com/image/cache/catalog/products/tesamorelin-600x600.png"
  }
];

export const FAQS_DATA: FAQItem[] = [
  {
    question: "Are peptides legal to purchase in the United Kingdom?",
    answer: "Yes. In the United Kingdom, peptides are completely legal to purchase and possess for laboratory research, in-vitro testing, and scientific analysis. However, under UK regulations, specifically the Human Medicines Regulations 2012, they cannot be marketed, sold, or supplied for human consumption or as medicinal treatments without authorisation from the MHRA (Medicines and Healthcare products Regulatory Agency)."
  },
  {
    question: "What does 'research-grade' signify?",
    answer: "Research-grade signifies that the substance is manufactured with ultra-high purity (typically 98% or higher, verified by HPLC and Mass Spectrometry) specifically for scientific research, in-vitro experiments, or diagnostic studies. These chemical compounds are strictly not approved for clinical therapy, human trials, or direct administration to humans or animals outside of a controlled laboratory environment."
  },
  {
    question: "How are the purity and quality of your peptides verified?",
    answer: "Every batch of peptides supplied by UK Peptide Labs undergoes a double-verification protocol. We perform High-Performance Liquid Chromatography (HPLC) to confirm purity profiles and Mass Spectrometry (MS) to verify molecular weight and sequence identity. Certificate of Analysis (CoA) reports are compiled for every production batch and are accessible upon request for verification."
  },
  {
    question: "How should lyophilised peptides be stored?",
    answer: "For short-term storage (under 4 weeks), lyophilised peptides can be kept at room temperature (around 20°C) away from direct sunlight. For long-term preservation, they must be stored in a freezer at -20°C to maintain stability and prevent degradation. Once reconstituted in a sterile solution (such as bacteriostatic water), they must be kept refrigerated at 2°C to 8°C and used within a limited research timeframe."
  },
  {
    question: "Do you offer UK-wide temperature-controlled shipping?",
    answer: "Yes, we ship to all addresses in the United Kingdom. All items are dispatched in highly insulated, climate-shielded packaging with cold-packs when necessary. We use tracked, next-day courier services (Royal Mail Tracked 24 or DHL Express) to ensure the structural integrity of the chemical crystals is preserved throughout transit."
  },
  {
    question: "Can UK Peptide Labs provide dosage instructions or protocols?",
    answer: "No. In strict compliance with UK regulations, we do not provide dosage guides, mixing ratios, therapeutic protocols, or administration instructions for humans or animals. Doing so would violate UK licensing rules regarding unlicensed medical advice. We encourage all researchers to refer to peer-reviewed scientific literature and established laboratory manuals."
  }
];
